# -*- coding: utf-8 -*-
"""normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15x-Z8rb5MbMVPJeeXgMlX6U_rikftGqg
"""

text="how are u doing!,blah"
normalized_text=text.lower()
normalized_text="".join([char for char in normalized_text if char.isalnum() or char.isspace()])
normalized_text="".join(normalized_text.split())
print(text)
print(normalized_text)