# -*- coding: utf-8 -*-
"""POS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBpkJkhM82cBpLit0r2k359HePQovv0B
"""

import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng') # Corrected resource name

from nltk.tokenize import word_tokenize

text="hello everyone"
words=word_tokenize(text)
pos_tags=nltk.pos_tag(words)
print(pos_tags)