# -*- coding: utf-8 -*-
"""q&a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlKJJryAtdkjsnxAsRNeHx477HOuFxik
"""

from transformers import pipeline

qa = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

context = "Hugging Face provides tools to download and apply state-of-the-art NLP models."
question = "What does Hugging Face provide?"

answer = qa(question=question, context=context)
print(answer)

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformers