# -*- coding: utf-8 -*-
"""stemming and lemmantazion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWoscEHle5JRiU_g3PSCWKroKfFDSZUw
"""

import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab') # Download the missing resource

text = "The cats were running and studying"

# Initialize stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Tokenize the sentence
words = word_tokenize(text)

# Stemming
stemmed_words = [stemmer.stem(word) for word in words]
print("Stemmed Words:", stemmed_words)

# Lemmatization
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
print("Lemmatized Words:", lemmatized_words)