# -*- coding: utf-8 -*-
"""stop words removal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m337bxbFcLECj0B8g6Y_ROW9rvvK4FYS
"""

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

#Remove stop words

import re
text=input("enter a text")
words=re.sub(r'[^\w\s]',"",text).split() #remove punctuation
filtered_words=[word for word in words if word not in stop_words]
print(stop_words)
print(filtered_words)