# -*- coding: utf-8 -*-
"""textblob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19J5vBS3Z8MjnS5KRZHYdLy7iib2ZlGz5
"""

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

from textblob import TextBlob
text="The quick brown fox jumps over the lazy dog"
blob=TextBlob(text)
for word,pos in blob.tags:
  print(word,pos)

import nltk
nltk.download('averaged_perceptron_tagger_eng')

import nltk
nltk.download('punkt_tab')