# -*- coding: utf-8 -*-
"""translator eng to french.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-xUMpBA1ek26QvRUYYIBZEdvUmu1EYc
"""

from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-en-fr"  # Change to any of the above
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

text = "Hello, how are you?"
inputs = tokenizer(text, return_tensors="pt", padding=True)
translated = model.generate(**inputs)
print(tokenizer.decode(translated[0], skip_special_tokens=True))